### Initialize Stagehand
GET http://localhost:3000/initConnection

### Navigate to a URL
POST localhost:3000/goto/7e645965-3a46-416e-9a09-8b061c11b348
Content-Type: application/json

{
  "url": "https://www.sme.sk/"
}

### Perform an action
POST localhost:3001/act/5c13888b-0b0f-41dc-8e3f-b6fe6fea649f
Content-Type: application/json

{
  "actAction": "Click on the top headline"
}


### Perform an action
POST localhost:3001/extract/5c13888b-0b0f-41dc-8e3f-b6fe6fea649f
Content-Type: application/json

{
  "extractAction": {
    "instruction":"Summarize the article"
  }
}

### Perform an action
# @timeout 30010
POST localhost:3000/agentExecute/7e645965-3a46-416e-9a09-8b061c11b348
Content-Type: application/json

{
  "instruction": "Click on top headline and summarize the page of that article"
}