### GET request to example server
POST https://cortx-gamma.vercel.app/api/terminal/route
Content-Type: application/json

{
    "command":"echo 'HELLO WORLD'",
    "sessionID":"jabadabadu",
    "apiKey":"skibiditoilet123"
}

###